### ISSUE TITLE
sqlalchemy_utils is not installed as a requirement

### ISSUE THREAD

**Issue by rsjethani** [ntt-sic/masakari#40]
While creating database like:
`openstack@openstack-VirtualBox:~/masakari/masakari_controller/db$ sudo ./create_database.sh
/home/openstack/masakari/masakari_controller/db
/home/openstack/masakari
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/openstack/masakari/masakari_controller/db/create_tables.py", line 22, in <module>
    from sqlalchemy_utils.functions import database_exists, create_database
ImportError: No module named sqlalchemy_utils.functions
`
we get import error for sqlalchemy_utils module. It should be mentioned in the masakari-controller/requirements.txt and should be installed as a dependency

**Comment by sampathP** [comment]
Hi, Thanks for the report.
I thought I resolved this by adding following line to masakari-controller/requirements.txt.
https://github.com/ntt-sic/masakari/blob/master/masakari-controller/requirements.txt#L14
SQLAlchemy-Utils>=0.32.0
Are you using the latest code (tag > 1.1.0) ?

**Comment by rsjethani** [comment]
Oh! yess

The latest master code has this requirement
